[2022-06-26 22:27:44] ERROR Error in Get Create Source Definitions Function!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 198, in get_create_source_definitions
    for i in range(0, len(attribute_name_list)):
UnboundLocalError: local variable 'attribute_name_list' referenced before assignment
