[2022-04-07 21:59:29] ERROR Error in Creating Source!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\serializers.py", line 46, in create
    os.mkdir(source_path_proper)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:/AdventsProduct/V1.0.0/AFS/Sources/Data/INVOICE_SALARY_REPORT_PM/input/'
[2022-04-07 22:02:09] ERROR Error in Creating Source!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\serializers.py", line 46, in create
    os.mkdir(source_path_proper)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:/AdventsProduct/V1.0.0/AFS/Sources/Data/INVOICE_SALARY_REPORT_PM/input/'
